#!/bin/bash

lib_number(){
    local path="/root/clilab/tools/lib/number"
    local file

    ##source##
    for file in "$path"/lib_number_*; do
        source "$file"
    done
}

# [check_range]: check value's range
# usage: lib_check_range [q] value [min] [max]
# 
# [check_int]:
#
# [nicenum]: 
