#!/bin/bash

lib_use(){
    local input="$1"; oldIFS="$IFS"; IFS=","

    for lib in $1; do
        case "$lib" in
            check)  source $HOME_LIB/lib_check ; lib_check ;;
            number) source $HOME_LIB/lib_number ; lib_number ;;
            *)      source "$HOME_LIB"/"$lib" ;;
        esac
    done

    IFS="$oldIFS"
}

lib_echo(){
    local quiet_mode="$1"
    local input="$2"
    
    if [ "$quiet_mode" = 0 ]; then
        echo "$input"
    fi

    return 0
}

#lib_debug(){
#    input="$1"; oldIFS="$IFS"; IFS=","
#    for str in $input; do
#        result=$result"$str"
